DExDI_app/DExDI_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pm_graphs/', include('pm_graphs.urls')),
    path('admin/', admin.site.urls),
]

DExDI_app/pm_graphs/urls.py
from django.urls import path

from . import views

app_name = 'dexdi'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload_file/', views.upload_file, name='upload_file'),
]

DExDI_app/pm_graphs/models.py
from django.db import models

# Create your models here.

DExDI_app/pm_graphs/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

DExDI_app/pm_graphs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import UploadFileForm
# Imaginary function to handle an uploaded file.
#from somewhere import handle_uploaded_file


def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def index(request):
    return render(request, 'pm_graphs/index.html')


def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'pm_graphs/upload_file.html', {'form': form})

DExDI_app/pm_graphs/templates/pm_graphs/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>DExDI</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'pm_graphs/style.css' %}">
  </head>
  <body>
    <h1>Detecting Exoplanets via Direct Imaging</h1>
    <p>Upload your observations via .csv or .json.</p>
    <p>Column names are main_id, cc_id, dates, dra, dra_err, ddec, ddec_err</p>
    <li><a href="{% url 'dexdi:upload_file' %}">Wanna upload a file?</a></li>
  </body>
</html>

DExDI_app/pm_graphs/templates/pm_graphs/name.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>DExDI</title>
  </head>
  <body>
    <p>Column names are main_id, cc_id, dates, dra, dra_err, ddec, ddec_err</p>
    <form action="/showname.html" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
  </body>
</html>

DExDI_app/pm_graphs/templates/pm_graphs/upload_file.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>DExDI</title>
  </head>
  <body>
    <p>Column names are main_id, cc_id, dates, dra, dra_err, ddec, ddec_err</p>
    <form action="/showname.html" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
  </body>
</html>